development:
  host: localhost
  database: tweets_nearby_development
  #autocreate_indexes: true
  #allow_dynamic_fields: true

test:
  host: localhost
  database: tweets_nearby_test
  #autocreate_indexes: true
  #allow_dynamic_fields: true

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOHQ_URL'] %>
  port: 10042
  username: heroku
  password: a76cea2d8a54af60e98b4f10bfcabc8e
  database: app1884419
  #username: <%= ENV['MONGOID_USERNAME'] %>
  #password: <%= ENV['MONGOID_PASSWORD'] %>
  #database: <%= ENV['MONGOID_DATABASE'] %>
  
  #allow_dynamic_fields: true
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
